export default {
  BLOCKCHAIN: "BLOCKCHAIN",
  TRANSACRION: "TRANSACTION",
  THREAD: "THREAD",
  THREAD_TITLE: "THREAD_TITLE",
  THREAD_RES: "THREAD_RES",
  SYSTEM: "SYSTEM",
  APP: "APP",
  NEWBLOCK: "NEWBLOCK",
  CONFLICT: "CONFLICT",
  RESOLVE_CONFLICT: "RESOLVE_CONFLICT",

  //kademlia
  STORE: "STORE",
  FINDNODE: "FINDNODE",
  FINDNODE_R: "FINDNODE_R",
  PING: "PING",
  PONG: "PONG",
  ONCOMMAND: "ONCOMMAND",
  ADD_KNODE: "ADD_KNODE",
  BLOADCAST: "BLOADCAST"
};
